# ビルドステージ
FROM node:20-alpine as build-stage

WORKDIR /app

# 依存関係のインストール
COPY package*.json ./
RUN npm install

# アプリケーションのソースコードをコピー
COPY . .

# Reactアプリケーションのビルド
RUN npm run build

# 本番ステージ
FROM nginx:alpine

# Reactアプリケーションのビルド成果物をNginxの提供ディレクトリにコピー
COPY --from=build-stage /app/build /usr/share/nginx/html

# Nginxのデフォルト設定を削除
RUN rm /etc/nginx/conf.d/default.conf

# カスタムNginx設定ファイルをコピー
COPY nginx.conf /etc/nginx/conf.d

# Nginxの起動
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
